### PR TITLE
Fix: RecyclerDataSource memory leak

### PR DESCRIPTION
**Pull request by ThisALV**
RecyclerDataSource wasn't deleted

### CODE REVIEW

**Comment by xfangfang** [comment]
Look good to me, I know this issue, but I didn't fix it because I'm afraid some applications may rely on this behavior, and maintain the dataSource themselves.
Before merging, I would like to ask @PoloNX @dragonflylee and @XITRIX if this will affect them.

- - -

btw, I am using another list in my own app, which supports variable height views or grid layout based on RecyclerList. If anyone is interested, I will synchronize it here.

https://github.com/xfangfang/wiliwili/blob/yoga/wiliwili/include/view/recycling_grid.hpp

**Comment by XITRIX** [comment]
To be honest I completely forgot the reason of why I commented it out, may be we could add `bool  releaseDataSourceOnDeinit` with true by default, in case someone would like to maintain datasource's lifecycle manually

**Comment by PoloNX** [comment]
> To be honest I completely forgot the reason of why I commented it out, may be we could add `bool releaseDataSourceOnDeinit` with true by default, in case someone would like to maintain datasource's lifecycle manually

It’s a good idea. I don’t need to maintain it personally

**Comment by dragonflylee** [comment]
maybe https://github.com/ITotalJustice/borealis/commit/842d4b290286c821065f0680610502edb1eb4d2e is another workaround solution

**Comment by ThisALV** [comment]
> maybe [ITotalJustice@842d4b2](https://github.com/ITotalJustice/borealis/commit/842d4b290286c821065f0680610502edb1eb4d2e) is another workaround solution

Yup seems to work. Now I remember when I de-commented those lines I had segfault on dropdown item selection and I didn't understand why. I'll add another commit to address the issue by applying ITotalJustice fix to the PR.

**Comment by ThisALV** [comment]
Okay I've done the commit, now there's an optional bool parameter on `setDataSource` allowing to prevent data source deletion by the RecyclerFrame and Dropdown constructor uses it.

**Comment by PoloNX** [comment]
> Okay I've done the commit, now there's an optional bool parameter on `setDataSource` allowing to prevent data source deletion by the RecyclerFrame and Dropdown constructor uses it.

If it defaults to true. Is it a breaking change?

**Pull request merged**
