### PR TITLE
Adding an overload for the function brls::loadTranslations

### PR DESCRIPTION
**Pull request by PoloNX**
I wanted to use translations which are not in the nintendo switch system. I added it, it will search in the romfs:/i18n if there is the translation

### CODE REVIEW

**Comment by PoloNX** [comment]
whoops my last commit

**Comment by xfangfang** [comment]
to set custom locale, you can do this:

brls::Platform::APP_LOCALE_DEFAULT = “some locale id”;

make sure this line is run before brls::Application::init()

**Comment by PoloNX** [comment]
And how do you load one specific translation after ?

**Comment by xfangfang** [comment]
restart the app?

I think Borealis does not support runtime switching unless all activities are manually removed and overloaded, which is similar to restarting the app.

**Comment by PoloNX** [comment]
I found it, it's good

**Pull request closed without merging**
