### PR TITLE
Axis support for LT and RT

### PR DESCRIPTION
**Pull request by XITRIX**

### CODE REVIEW

**Comment by xfangfang** [comment]
Thank you very much for your contribution. Your previous modifications to borealis (like touch and recyclerList) have been very helpful to me.
And good job for moonlight, Looking forward to seeing the borealis version of Moonlight on iOS.

**Comment by XITRIX** [comment]
I also want to thank you for improving borealis with so many different platforms support, if not this I don't think I've even started to think about porting my Moonlight app to iOS.

BTW, could you check [my branch](https://github.com/XITRIX/borealis) by yourself? I've started to upstream it with your fork, maybe I've added something you could would like to cherrypick as well, i.e. I'm not sure if you need my changes for MetalANGLE support on iOS, but maybe some improvements could fit your needs

**Comment by xfangfang** [comment]
Thank you. I will go check on them, probably over the weekend.

And I feel it's time to set the version label for Borealis, treating the original version as 1.0, the Yoga version as 2.0, and the current version as 3.0. If so, I will set the new version as 4.0.0, and release it after each major update. I hope this will make it easier for everyone to understand the update status of the project.

**Comment by XITRIX** [comment]
I think changing major version could scary devs from upgrading, like it was with v1 -> yoga update (and it was reasonable, it was almost a new library written from scratch), while currently I had no issues with migrating my yoga branch to current yours one, so I'd prefer to use something like v2.x

**Comment by xfangfang** [comment]
Yeah, then maybe 2.0 for the original yoga, 2.1 for the new release, I'll add some CI for different platform before the release.

**Pull request merged**
